### ISSUE TITLE
Move everything into a "web" directory

### ISSUE THREAD

**Issue by joefutrelle** [mayaapeterson/whoi-plankton#1]
Create a directory called "web" and move everything into it

**Comment by joefutrelle** [comment]
Also, reconfigure GitHub pages to use the "web" directory as the root directory

**Comment by mayaapeterson** [comment]
I created the "web" directory and moved all of the WHOI-plankton files into it. After our Slack discussion, I changed the "web" directory to be called "docs" on Pycharm and committed and pushed it to GitHub. I also reconfigured the "/(root)" directory on Git Pages to use "/docs" instead, so it could call the right file.
